services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - tasksdb:/app/tasksdb
    develop:
      watch:
        - action: rebuild
          path: ./templates
          target: /app/templates
        - action: rebuild
          path: ./cmd
        - action: rebuild
          path: ./pkg
volumes:
  tasksdb:
